### ISSUE TITLE
"deez.dll" was not found

### ISSUE THREAD

**Issue by GoldenretriverYT** [LuaBuilds/Windows-Builds#1]
Hello,
when I try to execute your Lua-Build i get following error:
"deez.dll was not found"a

**Comment by FreeBSoD** [comment]
DEEZ.DLL is needed because nuts are a thing. if you want to download DEEZ.DLL go to NUTS.COM and click download DEEZ.DLL.

**Comment by GoldenretriverYT** [comment]
Hello,
I was unable to find the download for DEEZ.dll on nuts.com. It appears to be an online shop for nuts, they do not offer any downloads.

**Comment by GoldenretriverYT** [comment]
hi
